config/routes.rb
MagicBox::Application.routes.draw do
  resources :applications do
  member do
  end
  collection do
    post "create_user"
    get  "index"
    get "input"
  end
  end

   root :to => 'applications#index'

end

app/models/box.rb
class Box < ActiveRecord::Base
  attr_accessible :name, :score, :time, :matrix

  validates :name, :presence => true
  validates :matrix, :presence => true

  def self.create_magic_matrix(params)
    order = params[:order]
    @result = Array.new(order.to_i) {Array.new(order.to_i)}
    k = 0
    order.to_i.times do | i |
      order.to_i.times do | j |
        @result[i][j] = params[:"#{k}"]
        k=k+1
      end
    end

    @result
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController

  def index
    @user = Box.new
  end

  def create_user
    @user = Box.new(params[:box])
    @user.save
  end

  def input
   @result = Box.create_magic_matrix(params)

  end

  def result
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/create_user.html.erb
<div id ="box">
  <h4>Lates Start </h4><h1> Magic Box!</h1>

  <%= label_tag 'Name'  %>
  <%= text_field_tag :name, @user.name, 'disabled' => true %> <br> <br>

  <%= label_tag 'Matrix'  %>
  <%= text_field_tag :matrix, @user.matrix, :id => 'matrix', 'disabled' => true %> <br> <br>

  <% @matrix = @user.matrix
  k = 0%>
    <%= form_tag input_applications_path, :method => "get" do |f| %>
    <% (1..@matrix).each do |i| %>

          <% (1..@matrix).each do |j| %>
              <%= text_field_tag "#{k}",nil, :class => 'value' %>
              <% k=k+1 %>
          <% end %>
            <br/>
    <% end %>
      <input type="hidden" name="order" value="<%=@user.matrix%>">
  <%= submit_tag %>
  <% end %>

  <div class="btn-group">
  </div>
</div>

app/views/applications/index.html.erb
<h3>Welcome to Magicbox</h3> <hr>
<h4>Please enter your name matrix number here</h4>
<div class="well sidebar-nav">
<%= form_for @user, :url => create_user_applications_path, :html => { :class => 'form-horizontal' } do |f| %>
      <% if @user.errors.any? %>
          <div id="error_explanation">
            <h4><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h4>

            <ul>
              <% @user.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :matrix, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :matrix, :class => 'text_field' %>
      </div>
    </div>


    <div class="form-actions">
      <%= f.submit  :class => 'btn btn-primary' %>
    </div>
     </div>
<% end %>

app/views/applications/input.html.erb
<%= @result.to_s %>

app/views/applications/new.html.erb
<%- model_class = @application.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "MagicBox" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">MagicBox</a>
          <div class="container nav-collapse">
            <!--<ul class="nav">-->
              <!--<li><%#= link_to "Link1", "/path1"  %></li>-->
              <!--<li><%#= link_to "Link2", "/path2"  %></li>-->
              <!--<li><%#= link_to "Link3", "/path3"  %></li>-->
            <!--</ul>-->
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
            <div class="span3">
              <!--<div class="well sidebar-nav">-->
                <!--<h3>Sidebar</h3>-->
                <!--<ul class="nav nav-list">-->
                  <!--<li class="nav-header">Sidebar</li>-->
                  <!--<li><%#= link_to "Link1", "/path1"  %></li>-->
                  <!--<li><%#= link_to "Link2", "/path2"  %></li>-->
                  <!--<li><%#= link_to "Link3", "/path3"  %></li>-->
                <!--</ul>-->
              <!--</div>&lt;!&ndash;/.well &ndash;&gt;-->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <!--<footer>-->
        <!--<p>&copy; Company 2012</p>-->
      <!--</footer>-->
    </div>
 <!--</div> &lt;!&ndash; /container &ndash;&gt;-->
    <!--&lt;!&ndash; Javascripts-->
    <!--================================================== &ndash;&gt;-->
    <!--&lt;!&ndash; Placed at the end of the document so the pages load faster &ndash;&gt;-->
    <%= javascript_include_tag "application" %>

  </body>
</html>